CREATE DATABASE MAKERTHON

USE MAKERTHON

CREATE TABLE USERINFO(
	U_ID INT IDENTITY(1, 1)	NOT NULL,
	USERNAME VARCHAR(255) NOT NULL,
	PWord VARCHAR(255) NOT NULL,
	CONSTRAINT PK_NGUOIDUNG PRIMARY KEY (U_ID)
);

CREATE TABLE VOCAB(
	U_ID INT NOT NULL,
	WORD VARCHAR(255) NOT NULL,
	MEANINGS VARCHAR(1028) NOT NULL,
	CONSTRAINT PK_VOCAB PRIMARY KEY (U_ID, WORD),
	CONSTRAINT FK_UID FOREIGN KEY (U_ID) REFERENCES USERINFO(U_ID)
)

CREATE PROCEDURE ADD_USER
	@username varchar(255),
	@password varchar(255)

AS
BEGIN
	IF EXISTS (SELECT 1 FROM USERINFO WHERE USERNAME = @username)
    BEGIN
        RAISERROR(N'Tài khoản "%s" đã được sử dụng!', 16, 1, @username);
        RETURN;
    END

END
DROP PROCEDURE GET_VOCAB_BY_ID
CREATE PROCEDURE GET_VOCAB_BY_ID
	@UID INT
AS
BEGIN 
	SELECT V.WORD, V.MEANINGS
	FROM VOCAB V
	WHERE V.U_ID = @UID
END;